### ISSUE TITLE
RuntimeError on dumps if dict is embedded into list.

### ISSUE THREAD

**Issue by Rotwang** [avakar/pytoml#18]
Hi,

my understanding is that toml is equivalent to json.
Lets consider following code:

```python
import pytoml as toml

# this is totally serializable to json but pytoml can't handle it
print toml.dumps({'foo': [{'quux': 'quuuux'}, 'bar']})
```

following trace occurs:
```
Traceback (most recent call last):
  File "./t", line 5, in <module>
    print toml.dumps({'foo': [{'quux': 'quuuux'}, 'bar']})
  File "/Users/b.palmowski/Library/Python/2.7/lib/python/site-packages/pytoml/writer.py", line 11, in dumps
    dump(fout, obj, sort_keys=sort_keys)
  File "/Users/b.palmowski/Library/Python/2.7/lib/python/site-packages/pytoml/writer.py", line 118, in dump
    fout.write('{0} = {1}\n'.format(_escape_id(k), _format_value(v)))
  File "/Users/b.palmowski/Library/Python/2.7/lib/python/site-packages/pytoml/writer.py", line 86, in _format_value
    return _format_list(v)
  File "/Users/b.palmowski/Library/Python/2.7/lib/python/site-packages/pytoml/writer.py", line 49, in _format_list
    return '[{0}]'.format(', '.join(_format_value(obj) for obj in v))
  File "/Users/b.palmowski/Library/Python/2.7/lib/python/site-packages/pytoml/writer.py", line 49, in <genexpr>
    return '[{0}]'.format(', '.join(_format_value(obj) for obj in v))
  File "/Users/b.palmowski/Library/Python/2.7/lib/python/site-packages/pytoml/writer.py", line 88, in _format_value
    raise RuntimeError(v)
RuntimeError: {'quux': 'quuuux'}
```

**Comment by avakar** [comment]
Hi, thanks for the issue!

Unfortunately, TOML and JSON are not equivalent. In this particular case, you're bumping into TOML's inability to represent heterogeneous arrays. For specs, see https://github.com/toml-lang/toml#user-content-array, especially the sentence "Data types may not be mixed [...]".

If you're searching for a human-readable format that is also expressive, I recommend CSON, the Coffeescript version of JSON. Which (shameless plug :) ) I also happen to have a python implementation for: https://github.com/avakar/pycson.

**Comment by Rotwang** [comment]
Thanks for correcting my misconception and blazingly fast response!
