### ISSUE TITLE
Pytoml chokes on input from rust thread_local Cargo.toml

### ISSUE THREAD

**Issue by nipunn1313** [avakar/pytoml#26]
I'm not sure exactly what it is about this line, but it causes pytoml to fail. If I remove the middle third, it will pass, but I'm not sure if it's the quotes, or the parens or something else.
```
[target.'cfg(not(target_os = "emscripten"))'.dependencies]
```
Source: https://github.com/Amanieu/thread_local-rs/blob/master/Cargo.toml

Failure:
```
>>> pytoml.loads(open('Cargo.toml').read())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/vagrant/client-dropbox-python/dropbox-virtual-env-3dfc741c0e6a-mac-intel-10.12/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pytoml/parser.py", line 23, in loads
    ast = _p_toml(src)
  File "/Users/vagrant/client-dropbox-python/dropbox-virtual-env-3dfc741c0e6a-mac-intel-10.12/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pytoml/parser.py", line 344, in _p_toml
    s.expect_eof()
  File "/Users/vagrant/client-dropbox-python/dropbox-virtual-env-3dfc741c0e6a-mac-intel-10.12/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pytoml/parser.py", line 124, in expect_eof
    return self._expect(self.consume_eof())
  File "/Users/vagrant/client-dropbox-python/dropbox-virtual-env-3dfc741c0e6a-mac-intel-10.12/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pytoml/parser.py", line 164, in _expect
    raise TomlError('msg', self._pos[0], self._pos[1], self._filename)
pytoml.core.TomlError: <string>(15, 1): msg
```

**Comment by avakar** [comment]
Sorry for the late response. I'll look into the issue immediately.

**Comment by avakar** [comment]
This is actually a feature of toml-0.4. Keys may not be enclosed by single quotes. See https://github.com/toml-lang/toml/blob/master/versions/en/toml-v0.4.0.md#table, where the keys follow the rules for "basic strings", and basic strings are always double-quoted.

The master version of toml changed that and now allowes "literal strings" as well.

I'm not going to support new features in toml, but if you want to submit a pull-request, I'm willing to merge it.
