### ISSUE TITLE
Parser fails on raw quote followed by escape inside multi-line basic string

### ISSUE THREAD

**Issue by jorisvr** [avakar/pytoml#48]
I get an error when I try to parse the following valid TOML document:

    a = """b "\n c"""

Result: `TomlError: <string>(1, 1): msg`
Expected: `{'a': 'b "\\n c'}`

**Comment by avakar** [comment]
Hi, this works for me, are you sure you have the latest version installed? If so, please post the entire call stack.

    >>> pytoml.loads('a = """b "\n c"""')
    {'a': 'b "\n c'}

**Comment by jorisvr** [comment]
I'm using the latest version of pytoml from github master.

Your Python statement tests a slightly different TOML document than the one I reported.
Note that the backslash symbol is a special symbol for Python. To get the backslash into the TOML parser, it needs to be escaped in the Python string.

    >>> pytoml.loads('a = """b "\\n c"""')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/joris/src/toml/pytoml/pytoml/parser.py", line 23, in loads
        ast = _p_toml(src, object_pairs_hook=object_pairs_hook)
      File "/home/joris/src/toml/pytoml/pytoml/parser.py", line 352, in _p_toml
        s.expect_eof()
      File "/home/joris/src/toml/pytoml/pytoml/parser.py", line 124, in expect_eof
        return self._expect(self.consume_eof())
      File "/home/joris/src/toml/pytoml/pytoml/parser.py", line 164, in _expect
        raise TomlError('msg', self._pos[0], self._pos[1], self._filename)
    pytoml.core.TomlError: <string>(1, 1): msg
